//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessOk.ModelFramework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessOk.ModelFramework.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can validate IEnumerable&lt;T&gt; only. Given type: {1}..
        /// </summary>
        internal static string CollectionValidatorInvalidObject {
            get {
                return ResourceManager.GetString("CollectionValidatorInvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can validate strings and arrays only. Given type: {1}..
        /// </summary>
        internal static string LengthValidatorInvalidObject {
            get {
                return ResourceManager.GetString("LengthValidatorInvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not have negative Length property. Given: {1}..
        /// </summary>
        internal static string LengthValidatorNegativeLength {
            get {
                return ResourceManager.GetString("LengthValidatorNegativeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a string or array type with a maximum length of &apos;{0}&apos;..
        /// </summary>
        internal static string MaxLengthValidatorMessage {
            get {
                return ResourceManager.GetString("MaxLengthValidatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a string or array type with a minimum length of &apos;{0}&apos;..
        /// </summary>
        internal static string MinLengthValidatorMessage {
            get {
                return ResourceManager.GetString("MinLengthValidatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required.
        /// </summary>
        internal static string NotNullValidatorMessage {
            get {
                return ResourceManager.GetString("NotNullValidatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be empty.
        /// </summary>
        internal static string NullValidatorMessage {
            get {
                return ResourceManager.GetString("NullValidatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required.
        /// </summary>
        internal static string ObsoleteValidationContextRequiredField {
            get {
                return ResourceManager.GetString("ObsoleteValidationContextRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error.
        /// </summary>
        internal static string ObsoleteValidationContextValidationError {
            get {
                return ResourceManager.GetString("ObsoleteValidationContextValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required.
        /// </summary>
        internal static string PresenceValidatorMessage {
            get {
                return ResourceManager.GetString("PresenceValidatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must match the regular expression &apos;{0}&apos;..
        /// </summary>
        internal static string RegularExpressionMessage {
            get {
                return ResourceManager.GetString("RegularExpressionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can validate DateTime only. Given type: {1}..
        /// </summary>
        internal static string SqlDateTimeValidatorInvalidObject {
            get {
                return ResourceManager.GetString("SqlDateTimeValidatorInvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите дату позднее 1753 года.
        /// </summary>
        internal static string SqlDateTimeValidatorMessage {
            get {
                return ResourceManager.GetString("SqlDateTimeValidatorMessage", resourceCulture);
            }
        }
    }
}
